config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "dashboard#index"
  resources :animals do
    resources :reservations, only: [:create]
  end
  resources :reservations, only: [] do
    member do
      patch 'accept'
      patch 'decline'
    end
  end
  get 'animals', to: 'animals#index', as: 'filtered_animals'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :reservations

  validates :nom, :presence, :especes, :age, :localisation, :prix, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :animal

  validates :date_debut, :date_fin, presence: true
  validate :end_date_after_start_date

  def end_date_after_start_date
    return if date_fin.blank? || date_debut.blank?

    if date_fin < date_debut
      errors.add(:date_fin, "doit être après la date de début")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :animals
  has_many :reservations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @cats = Animal.where(especes: 'Cat')
    @dogs = Animal.where(especes: 'Dog')
    @rodents = Animal.where(especes: 'Rodent')
    @reptiles = Animal.where(especes: 'Reptile')
    @fishes = Animal.where(especes: 'Fish')
    @birds = Animal.where(especes: 'Bird')
    unless params[:localisation].nil? || params[:localisation].empty?
      @cats = @cats.where(localisation: params[:localisation])
      @dogs = @dogs.where(localisation: params[:localisation])
      @rodents = @rodents.where(localisation: params[:localisation])
      @reptiles = @reptiles.where(localisation: params[:localisation])
      @fishes = @fishes.where(localisation: params[:localisation])
      @birds = @birds.where(localisation: params[:localisation])
    end
  end

  def show
    @animal = Animal.find(params[:id])
  end
  def new
    @animal = Animal.new
  end
  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user

    if @animal.save
      redirect_to dashboard_path, notice: 'L\'animal a bien été créé.'
    else
      render :new
    end
  end

  private

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:nom, :especes, :age, :localisation, :prix, :photo_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservations.includes(:animal)
    @animals = current_user.animals
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_animal

  def create
    @reservation = @animal.reservations.new(reservation_params)
    @reservation.user = current_user

    if @reservation.save
      redirect_to dashboard_path, notice: 'Réservation créée avec succès.'
    else
      redirect_to animal_path(@animal), alert: 'Erreur lors de la création de la réservation.'
    end
  end

  private

  def set_animal
    @animal = Animal.find(params[:animal_id])
  end

  def reservation_params
    params.require(:reservation).permit(:date_debut, :date_fin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.erb
<h1 class="text-center pt-4 my-4">Find your next Pet Pal !</h1>

<!-- Navbar des onglets -->
<div class="container mt-5">
  <ul class="nav nav-tabs justify-content-center" id="animalTabs" role="tablist">
    <li class="nav-item flex-fill text-center" role="presentation">
      <a class="nav-link active d-flex flex-column align-items-center round" id="cats-tab" data-bs-toggle="tab" href="#cats" role="tab" aria-controls="cats" aria-selected="true">
        <%= image_tag 'icons/cat_icon.png', style: 'width: 40px; height: 40px;', alt: 'Cat Icon' %>
        <span>Cats</span>
      </a>
    </li>
    <li class="nav-item flex-fill text-center" role="presentation">
      <a class="nav-link d-flex flex-column align-items-center rounded-top" id="dogs-tab" data-bs-toggle="tab" href="#dogs" role="tab" aria-controls="dogs" aria-selected="false">
        <%= image_tag 'icons/dog_icon.png', style: 'width: 40px; height: 40px;', alt: 'Dog Icon' %>
        <span>Dogs</span>
      </a>
    </li>
    <li class="nav-item flex-fill text-center" role="presentation">
      <a class="nav-link d-flex flex-column align-items-center rounded-top" id="rodents-tab" data-bs-toggle="tab" href="#rodents" role="tab" aria-controls="rodents" aria-selected="false">
        <%= image_tag 'icons/rabbit_icon.png', style: 'width: 40px; height: 40px;', alt: 'Rabbit Icon' %>
        <span>Rodents</span>
      </a>
    </li>
    <li class="nav-item flex-fill text-center" role="presentation">
      <a class="nav-link d-flex flex-column align-items-center rounded-top" id="reptiles-tab" data-bs-toggle="tab" href="#reptiles" role="tab" aria-controls="reptiles" aria-selected="false">
        <%= image_tag 'icons/snake_icon.png', style: 'width: 40px; height: 40px;', alt: 'Snake Icon' %>
        <span>Reptiles</span>
      </a>
    </li>
    <li class="nav-item flex-fill text-center" role="presentation">
      <a class="nav-link d-flex flex-column align-items-center rounded-top" id="fishes-tab" data-bs-toggle="tab" href="#fishes" role="tab" aria-controls="fishes" aria-selected="false">
        <%= image_tag 'icons/fish_icon.png', style: 'width: 40px; height: 40px;', alt: 'Fish Icon' %>
        <span>Fishes</span>
      </a>
    </li>
    <li class="nav-item flex-fill text-center" role="presentation">
      <a class="nav-link d-flex flex-column align-items-center rounded-top" id="birds-tab" data-bs-toggle="tab" href="#birds" role="tab" aria-controls="birds" aria-selected="false">
        <%= image_tag 'icons/toucan_icon.png', style: 'width: 40px; height: 40px;', alt: 'Toucan Icon' %>
        <span>Birds</span>
      </a>
    </li>
  </ul>
  <div class="tab-content" id="animalTabsContent">
    <!-- Onglet Cats -->
    <div class="tab-pane fade show active" id="cats" role="tabpanel" aria-labelledby="cats-tab">
      <div class="row mt-3">
        <% @cats.each_slice(4) do |cats_slice| %>
          <% cats_slice.each do |cat| %>
            <div class="col-md-3 mb-3">
              <%= link_to animal_path(cat), class: 'text-decoration-none text-dark' do %>
                <div class="card">
                  <img src="<%= cat.photo_url %>" class="card-img-top" alt="Cat Image">
                  <div class="card-body">
                    <h5 class="card-title"><%= cat.nom %></h5>
                    <p class="card-text"><%= cat.prix %>$ / day</p>
                    <p class="card-text"><%= cat.localisation %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Onglet Dogs -->
    <div class="tab-pane fade" id="dogs" role="tabpanel" aria-labelledby="dogs-tab">
      <div class="row mt-3">
        <% @dogs.each_slice(4) do |dogs_slice| %>
          <% dogs_slice.each do |dog| %>
            <div class="col-md-3 mb-3">
              <%= link_to animal_path(dog), class: 'text-decoration-none text-dark' do %>
                <div class="card">
                  <img src="<%= dog.photo_url %>" class="card-img-top" alt="Dog Image">
                  <div class="card-body">
                    <h5 class="card-title"><%= dog.nom %></h5>
                    <p class="card-text"><%= dog.prix %>$ / day</p>
                    <p class="card-text"><%= dog.localisation %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Onglet Rodents -->
    <div class="tab-pane fade" id="rodents" role="tabpanel" aria-labelledby="rodents-tab">
      <div class="row mt-3">
        <% @rodents.each_slice(4) do |rodents_slice| %>
          <% rodents_slice.each do |rodent| %>
            <div class="col-md-3 mb-3">
              <%= link_to animal_path(rodent), class: 'text-decoration-none text-dark' do %>
                <div class="card">
                  <img src="<%= rodent.photo_url %>" class="card-img-top" alt="Rodent Image">
                  <div class="card-body">
                    <h5 class="card-title"><%= rodent.nom %></h5>
                    <p class="card-text"><%= rodent.prix %>$ / day</p>
                    <p class="card-text"><%= rodent.localisation %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Onglet Reptiles -->
    <div class="tab-pane fade" id="reptiles" role="tabpanel" aria-labelledby="reptiles-tab">
      <div class="row mt-3">
        <% @reptiles.each_slice(4) do |reptiles_slice| %>
          <% reptiles_slice.each do |reptile| %>
            <div class="col-md-3 mb-3">
              <%= link_to animal_path(reptile), class: 'text-decoration-none text-dark' do %>
                <div class="card">
                  <img src="<%= reptile.photo_url %>" class="card-img-top" alt="Reptile Image">
                  <div class="card-body">
                   <h5 class="card-title"><%= reptile.nom %></h5>
                    <p class="card-text"><%= reptile.prix %>$ / day</p>
                    <p class="card-text"><%= reptile.localisation %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Onglet Fishes -->
    <div class="tab-pane fade" id="fishes" role="tabpanel" aria-labelledby="fishes-tab">
      <div class="row mt-3">
        <% @fishes.each_slice(4) do |fishes_slice| %>
          <% fishes_slice.each do |fish| %>
            <div class="col-md-3 mb-3">
              <%= link_to animal_path(fish), class: 'text-decoration-none text-dark' do %>
                <div class="card">
                  <img src="<%= fish.photo_url %>" class="card-img-top" alt="Fish Image">
                  <div class="card-body">
                    <h5 class="card-title"><%= fish.nom %></h5>
                    <p class="card-text"><%= fish.prix %>$ / day</p>
                    <p class="card-text"><%= fish.localisation %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Onglet Birds -->
    <div class="tab-pane fade" id="birds" role="tabpanel" aria-labelledby="birds-tab">
      <div class="row mt-3">
        <% @birds.each_slice(4) do |birds_slice| %>
          <% birds_slice.each do |bird| %>
            <div class="col-md-3 mb-3">
              <%= link_to animal_path(bird), class: 'text-decoration-none text-dark' do %>
                <div class="card">
                  <img src="<%= bird.photo_url %>" class="card-img-top" alt="Bird Image">
                  <div class="card-body">
                    <h5 class="card-title"><%= bird.nom %></h5>
                    <p class="card-text"><%= bird.prix %>$ / day</p>
                    <p class="card-text"><%= bird.localisation %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- footer -->
<%= render 'shared/footer' %>

app/views/animals/new.html.erb
<div class="container">
  <%= link_to dashboard_path, class: 'btn btn-secondary mt-3 retour mb-4', style: 'border-radius: 50px;' do %>
    <i class="fas fa-arrow-left"></i> Dashboard
  <%end%>

  <h1 class="mb-4">Rent a New Pet</h1>

  <%= form_with(model: @animal, local: true, class: "mb-4") do |form| %>
    <div class="form-group mb-3">
      <%= form.label :nom, class: "font-weight-bold mb-2" %>
      <%= form.text_field :nom, class: "form-control new " %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :especes, class: "font-weight-bold mb-2" %>
      <%= form.select :especes, ['Cat', 'Dog', 'Fish', 'Reptile', 'Rodent', 'Bird'], { prompt: "Select Species" }, class: "form-control new" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :age, class: "font-weight-bold mb-2" %>
      <%= form.number_field :age, class: "form-control border new" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :localisation, class: "font-weight-bold mb-2" %>
      <%= form.text_field :localisation, class: "form-control new" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :prix, class: "font-weight-bold mb-2" %>
      <%= form.number_field :prix, class: "form-control new" %>
    </div>

    <div>
    <%= form.label :photo_url, class: "font-weight-bold mb-2"%>
    <%= form.text_field :photo_url, class: "form-control new"%>
  </div>

    <div class="text-right mt-4">
      <%= form.submit "Submit", class: "btn btn-primary back" %>
    </div>
  <% end%>



  </div>

app/views/animals/show.html.erb
<%= link_to animals_path, class: 'btn btn-secondary mt-3 retour', style: 'border-radius: 50px;' do %>
  <i class="fas fa-arrow-left"></i> Pet pals list
<% end %>

<div class="container mb-4">
  <div class="row">
    <div class="col-md-6">
      <h1 class="text-left pt-4 mb-4"><%= @animal.nom %></h1>
      <div class="animal-info">
        <p><strong>Espèce:</strong> <%= @animal.especes.capitalize %></p>
        <p><strong>Âge:</strong> <%= @animal.age %> ans</p>
        <p><strong>Localisation:</strong> <%= @animal.localisation %></p>
        <p><strong>Prix:</strong> <%= number_to_currency(@animal.prix, locale: :fr) %></p>
      </div>
      <%= form_with model: [@animal, Reservation.new], local: true, class: 'mt-3' do |form| %>
        <div class="form-group">
          <%= form.label :date_debut, "Date de début" %>
          <%= form.date_field :date_debut, class: 'form-control', style: 'width: 100%; max-width: 300px; border-radius: 50px;' %>
        </div>
        <div class="form-group">
          <%= form.label :date_fin, "Date de fin" %>
          <%= form.date_field :date_fin, class: 'form-control', style: 'width: 100%; max-width: 300px; border-radius: 50px;' %>
        </div>
        <%= form.submit 'Book that pet', class: 'btn btn-primary reserver', style: 'border-radius: 50px;' %>
      <% end %>
    </div>
    <div class="col-md-6 d-flex align-items-start">
      <%= image_tag @animal.photo_url, alt: @animal.nom, class: 'img-fluid rounded shadow-sm' %>
    </div>
  </div>
</div>

<!-- footer -->
<%= render 'shared/footer' %>

app/views/dashboard/index.html.erb
<section class="pt-5 pb-5">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h3 class="mb-3">My Animals</h3>
      </div>
      <div class="col-6 d-flex justify-content-end">
        <a class="btn btn-primary mb-3 mr-1 back" href="#carouselAnimals" role="button" data-slide="prev">
          <i class="fa fa-arrow-left"></i>
        </a>
        <a class="btn btn-primary mb-3 back" href="#carouselAnimals" role="button" data-slide="next">
          <i class="fa fa-arrow-right"></i>
        </a>
      </div>
      <div class="col-12">
        <div id="carouselAnimals" class="carousel slide" data-ride="carousel" data-interval="false">
          <div class="carousel-inner">
            <% @animals.each_slice(3).with_index do |animal_slice, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>">
                <div class="row">
                  <% animal_slice.each do |animal| %>
                    <div class="col-md-4 mb-3">
                      <div class="card">
                        <%= image_tag animal.photo_url, class: 'img-fluid' %>
                        <div class="card-body">
                          <h4 class="card-title"><%= animal.nom %></h4>
                          <p class="card-text"><%= number_to_currency(animal.prix, unit: "$") %></p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<%= link_to 'Rent my pet', new_animal_path, class: "btn btn-primary back" %>

    <div class="row mt-5">
      <div class="col-6">
        <h3 class="mb-3">My Reservations</h3>
      </div>
      <div class="col-6 d-flex justify-content-end">
        <a class="btn btn-primary mb-3 mr-1 back" href="#carouselReservations" role="button" data-slide="prev">
          <i class="fa fa-arrow-left"></i>
        </a>
        <a class="btn btn-primary mb-3 back" href="#carouselReservations" role="button" data-slide="next">
          <i class="fa fa-arrow-right"></i>
        </a>
      </div>
      <div class="col-12">
        <div id="carouselReservations" class="carousel slide" data-ride="carousel" data-interval="false">
          <div class="carousel-inner">
            <% if @reservations.any? %>
              <% @reservations.each_slice(3).with_index do |reservation_slice, index| %>
                <div class="carousel-item <%= 'active' if index == 0 %>">
                  <div class="row">
                    <% reservation_slice.each do |reservation| %>
                      <div class="col-md-4 mb-3">
                        <div class="card">
                          <%= image_tag reservation.animal.photo_url, class: 'img-fluid' %>
                          <div class="card-body">
                            <h4 class="card-title"><%= reservation.animal.nom %></h4>
                            <p class="card-text">Species: <%= reservation.animal.especes %></p>
                            <p class="card-text">Price: <%= number_to_currency(reservation.animal.prix, unit: "$") %></p>
                            <p class="card-text">Start Date: <%= reservation.date_debut %></p>
                            <p class="card-text">End Date: <%= reservation.date_fin %></p>
                            <p class="card-text">Status: <%= reservation.statut %></p>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="carousel-item active">
                <div class="row">
                  <div class="col-md-12">
                    <p>You have no reservations</p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<%= link_to "All animals", animals_path, class: "btn btn-primary back" %>
  </div>
</section>


<!-- JavaScript dependencies -->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetPals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main class="landing-page">
    <section class="text-center landing-content">
      <h1>Welcome to PetPals!</h1>
      <p class="lead">Rent your perfect companion today.</p>
      <a href="/animals" class="btn btn-info btn-xl mt-3 text-white">View Pals</a>
    </section>
  </main>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-light py-4 w-100 mt-auto" id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 text-center mb-3 mb-md-0">
        <h5 class="footerH5">Contact Us</h5>
        <p>
          Email: <span class="email-contact">support@petpals.com</span> <br>
          Phone: +1 234 567 890
        </p>
      </div>
      <div class="col-md-4 text-center mb-3 mb-md-0">
        <h5 class="footerH5">Follow Us</h5>
        <a href="#" class="text-light mx-2"><i class="fab fa-facebook icon-large"></i></a>
        <a href="#" class="text-light mx-2"><i class="fab fa-twitter icon-large"></i></a>
        <a href="#" class="text-light mx-2"><i class="fab fa-instagram icon-large"></i></a>
        <a href="#" class="text-light mx-2"><i class="fab fa-tiktok icon-large"></i></a>
      </div>
      <div class="col-md-4 text-center">
        <h5 class="footerH5">Newsletter</h5>
        <form class="form-inline justify-content-center">
          <div class="input-group">
            <input type="email" class="form-control" placeholder="Enter your email" aria-label="Email" aria-describedby="subscribe-button">
            <div class="input-group-append">
              <button class="btn btn-primary" type="submit" id="subscribe-button">Subscribe</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col text-center">
        <p id="copyright">&copy; 2024 PetPals. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
     <%= link_to root_path, class: "navbar-brand" do %>
    <div class= "logo-css">
      <%= image_tag "icons/pawprint_logo.png" %>
      <h1>PetPals</h1>
    </div>
  <% end %>


<section class="search">
  <div class="container text-center no-marign">
    <form class="d-flex justify-content-center" method="get" action="<%= filtered_animals_path %>">
      <div class="input-group mb-2" style="max-width: 600px; width: 100%;">
        <select name="localisation" class="form-control" style="max-width: 200px;">
          <option value="">Select Region</option>
          <% Animal.distinct.pluck(:localisation).sort.each do |localisation| %>
            <option value="<%= localisation %>" <%= 'selected' if params[:localisation] == localisation %>><%= localisation %></option>
          <% end %>
        </select>
        <div class="input-group-append">
          <button type="submit" class="btn btn-primary">Search</button>

        </div>
      </form>
    </div>
  </section>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent your pet", new_animal_path, class: "nav-link offre"%>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://cdn.icon-icons.com/icons2/1949/PNG/512/free-30-instagram-stories-icons53_122600.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to 'Dashboard', dashboard_path, class: "dropdown-item" %>
              <%= link_to "Messages", "#", class: "dropdown-item" %>
              <%= link_to "Notifications", "#", class: "dropdown-item" %>
              <%= link_to "Animaux", "#", class: "dropdown-item" %>
              <%= link_to "Favoris", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>